name: Build PS3 Toolchain

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Code
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake bison flex g++ libelf-dev make texinfo libncurses5-dev patch pdf2svg libtool libtool-bin wget bzip2 gzip libgmp3-dev libmpfr-dev libmpc-dev zlib1g-dev git pkg-config Python3

      - name: Build SDK
        run: |
          export PS3DEV=/opt/ps3dev
          export PATH=$PATH:$PS3DEV/bin
          git clone https://github.com/ps3dev/ps3toolchain.git
          cd ps3toolchain
          sudo ./toolchain.sh

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: PS3DEV-Precompiled-SDK
          path: /opt/ps3dev
